version: '3.8'

services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:management
    ports:
      - "8081:15672"  # Maps RabbitMQ's default management port 15672 to 8081 on your host machine
      - "5672:5672"    # Default RabbitMQ port for messaging
    environment:
      RABBITMQ_DEFAULT_USER: dev   # Set the default user
      RABBITMQ_DEFAULT_PASS: dev  # Set the default password
